using YoutubeDLSharp;
using YoutubeDLSharp.Options;

namespace MyVideoArchive.Services.Content.Providers;

/// <summary>
/// Applies the configured <c>Subtitles</c> section of appsettings to a yt-dlp <see cref="OptionSet"/>
/// and provides a shared "subtitles-only" download routine used by <see cref="IVideoDownloader"/>
/// implementations. Subtitles are always converted to WebVTT so the browser's &lt;track&gt; element
/// (and video.js) can render them without a server-side transcoding step.
/// </summary>
internal static class SubtitleOptionsExtensions
{
    public const string SubtitleFormat = "vtt";

    /// <summary>
    /// Returns true when the user has opted in to subtitle downloads.
    /// </summary>
    public static bool AreSubtitlesEnabled(IConfiguration configuration)
        => configuration.GetValue<bool>("Subtitles:Enabled", false);

    /// <summary>
    /// Mutates an existing <see cref="OptionSet"/> used by a full video download so yt-dlp will
    /// also write sidecar subtitle files alongside the video.
    /// </summary>
    public static void ApplySubtitleOptions(OptionSet options, IConfiguration configuration)
    {
        if (!AreSubtitlesEnabled(configuration))
        {
            return;
        }

        PopulateSubtitleOptions(options, configuration);
    }

    /// <summary>
    /// Downloads *only* the sidecar subtitle files for a video (no video, no thumbnail, no info.json).
    /// Used by the subtitle backfill job to populate subs for videos that were downloaded before
    /// subtitles were enabled.
    /// </summary>
    public static async Task<bool> RunSubtitleOnlyDownloadAsync(
        YoutubeDL ytdl,
        ILogger logger,
        IConfiguration configuration,
        string videoUrl,
        string outputPath,
        CancellationToken cancellationToken)
    {
        if (!AreSubtitlesEnabled(configuration))
        {
            return false;
        }

        if (!Directory.Exists(outputPath))
        {
            Directory.CreateDirectory(outputPath);
        }

        var options = new OptionSet
        {
            SkipDownload = true,
            Output = Path.Combine(outputPath, "%(id)s.%(ext)s"),
            NoPlaylist = true
        };

        PopulateSubtitleOptions(options, configuration);

        var result = await ytdl.RunVideoDownload(videoUrl, overrideOptions: options, ct: cancellationToken);

        if (!result.Success)
        {
            string errorMessage = string.Join(", ", result.ErrorOutput);
            if (logger.IsEnabled(LogLevel.Warning))
            {
                logger.LogWarning(
                    "yt-dlp failed to download subtitles for {Url}: {Error}",
                    videoUrl, errorMessage);
            }
            return false;
        }

        return true;
    }

    private static void PopulateSubtitleOptions(OptionSet options, IConfiguration configuration)
    {
        string languages = configuration.GetValue<string>("Subtitles:Languages") ?? "en.*,en";
        bool includeAuto = configuration.GetValue<bool>("Subtitles:IncludeAutoGenerated", true);
        bool embed = configuration.GetValue<bool>("Subtitles:EmbedInVideo", false);

        options.WriteSubs = true;
        options.WriteAutoSubs = includeAuto;
        options.SubLangs = languages;
        options.ConvertSubs = SubtitleFormat;

        if (embed)
        {
            options.EmbedSubs = true;
        }
    }
}
