using YoutubeDLSharp.Options;

namespace MyVideoArchive.Tests.Services;

public class SubtitleOptionsExtensionsTests
{
    [Fact]
    public void AreSubtitlesEnabled_DefaultsToFalse()
    {
        var config = new ConfigurationBuilder().Build();
        Assert.False(SubtitleOptionsExtensions.AreSubtitlesEnabled(config));
    }

    [Fact]
    public void AreSubtitlesEnabled_RespectsSubtitlesEnabledFlag()
    {
        var config = new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?> { ["Subtitles:Enabled"] = "true" })
            .Build();
        Assert.True(SubtitleOptionsExtensions.AreSubtitlesEnabled(config));
    }

    [Fact]
    public void ApplySubtitleOptions_WhenDisabled_DoesNotMutateOptionSet()
    {
        var config = new ConfigurationBuilder().Build();
        var options = new OptionSet();
        SubtitleOptionsExtensions.ApplySubtitleOptions(options, config);
        Assert.False(options.WriteSubs);
    }

    [Fact]
    public void ApplySubtitleOptions_WhenEnabled_SetsWriteSubsAndConvertSubs()
    {
        var config = new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["Subtitles:Enabled"] = "true",
                ["Subtitles:Languages"] = "en",
                ["Subtitles:IncludeAutoGenerated"] = "false",
                ["Subtitles:EmbedInVideo"] = "true"
            })
            .Build();
        var options = new OptionSet();
        SubtitleOptionsExtensions.ApplySubtitleOptions(options, config);

        Assert.True(options.WriteSubs);
        Assert.False(options.WriteAutoSubs);
        Assert.Equal("en", options.SubLangs);
        Assert.Equal(SubtitleOptionsExtensions.SubtitleFormat, options.ConvertSubs);
        Assert.True(options.EmbedSubs);
    }
}